### PR TITLE
TicketStatusService and TicketPriority Mock

### PR DESCRIPTION
**Pull request by diegosilvestri**
TicketStatusService and TicketPriority Mock with all method implementation

### CODE REVIEW

**Comment by diegosilvestri** [comment]
Conflict Resolved

**Comment by diego81b** [comment]
idk but there are still some services injected as Transient.
I'm pretty sure that @amerlin as already fix them

**Review by diegosilvestri — COMMENTED** [review]
Merge with the latest pull request

**Review by amerlin — APPROVED** [review]

**Comment by diegosilvestri** [comment]
va ben non so cosa non va la cancello

**Comment by diegosilvestri** [comment]
PR Closed by mistake

**Comment by diegosilvestri** [comment]
Resolve Conflict

**Comment by diegosilvestri** [comment]
Closed

**Pull request closed without merging**
