### PR TITLE
ICrudService added

### PR DESCRIPTION
**Pull request by amerlin**
ICrudService added
TicketService added

### CODE REVIEW

**Review by diego81b — COMMENTED** [review]
- Generic parameter T and K are the same, so can be simplified to only one
- instead of type int should be useful to use a generic parameter TKey
- Related to T and K,  i'll create a constraint to a generic interface IEntity useful for dependency injection

Let me know if u want to review together
Cheer

**Review by amerlin — COMMENTED** [review]
fixed

**Review by diego81b — COMMENTED** [review]
Just a question (and last):
TicketService is a generic or a specialized class?
In case of specialized T and TKey must be the implemented type of Ticket entity
In case if generic class the class name should be CrudService

**Comment by amerlin** [comment]
> Just a question (and last):
> TicketService is a generic or a specialized class?
> In case of specialized T and TKey must be the implemented type of Ticket entity
> In case if generic class the class name should be CrudService

Actually there isn't a Ticket class :-) 
So this code need refactoring

**Review by diego81b — APPROVED** [review]

**Pull request merged**
