### PR TITLE
mudblazor and models

### PR DESCRIPTION
**Pull request by kasuken**

### CODE REVIEW

**Review by abbadon1334 — DISMISSED** [review]

**Comment by abbadon1334** [comment]
"src/PolarisDesk.IdentityProvider/AspIdUsers.db" <-- will be in conflict on any future changes.
I think the best solution is to remove it and add to gitignore and change reseeding method using the IS4 appsettings.json

**Comment by diego81b** [comment]
In my opinion the best way is to use Sql Server and the migration
At least we can use the same database as the api server but with a different schema

**Comment by abbadon1334** [comment]
> In my opinion the best way is to use SQL Server and the migration
> At least we can use the same database as the API server but with a different schema

if this is the way we must remove the SQLite file to avoid conflict and continue here the change of persistence.

For different schema you mean to use only for auth and  ACL and the rest of the models in the API?
I ask it only to better understand the dynamics behind

**Comment by diego81b** [comment]
> > In my opinion the best way is to use SQL Server and the migration
> > At least we can use the same database as the API server but with a different schema
> 
> if this is the way we must remove the SQLite file to avoid conflict and continue here the change of persistence.
> 
> For different schema you mean to use only for auth and ACL and the rest of the models in the API?
> I ask it only to better understand the dynamics behind

For different schema I mean that default schema of migrations is `dbo`.
So for a better mantainance of the db i suggest to use same db with:
1 - `dbo` schema for business model
2 - `auth` schema or similar for the use models

another point in favor of having the same db engine is the simplicity in using views, stored and permissions .

Last but not least Sqlite sucks

**Review by Valecass — APPROVED** [review]

**Comment by valentinotheworld** [comment]
ok

**Comment by valentinotheworld** [comment]
riapro

**Review by abbadon1334 — APPROVED** [review]

**Review by Valecass — APPROVED** [review]

**Review by valentinotheworld — APPROVED** [review]
tutto ok

**Review by abbadon1334 — APPROVED** [review]

**Review by amerlin — APPROVED** [review]

**Pull request closed without merging**
